reference_genome: '/shahlab/pipelines/reference/GRCh37-lite.fa'
results_dir: '/shahlab/pye/projects/biof34/BC/results/'
bam_directory: '/shahlab/pye/projects/biof34/BC/bams/'
bed_file: '/home/pye/ctDNA_pypeliner/beds/GRCh37.bed'
r_script_dir: '/home/pye/ctDNA_pypeliner/ctDNA/r_scripts/'
museq_python: '/shahlab/pipelines/virtual_environments/museq_pipeline/bin/python'
museq_classify: '/shahlab/pipelines/apps_centos6/mutationSeq_4.3.7_python2.7/classify.py'
museq_deep_model: '/shahlab/pipelines/apps_centos6/mutationSeq_4.3.7_python2.7/model_deep_v0.2.npz'
museq_config: '/shahlab/pipelines/apps_centos6/mutationSeq_4.3.7_python2.7/metadata.config'
snv_vcf_template: '/home/pye/ctDNA_pypeliner/template_snv.vcf'
indel_vcf_template: '/home/pye/ctDNA_pypeliner/template_indel.vcf'
annovar: '/shahlab/pye/software/annovar/'
annovar_humandb: '/shahlab/pye/software/annovar/humandb/'