reference_genome: '/Users/pye/projects/ctdna/hg19.fa'
results_dir: '/Users/pye/BIOF-34/results/'
bed_file: '/Users/pye/BIOF-34/ctDNA_pypeliner/beds/CG001v4.0.bed'
r_script_dir: '/Users/pye/BIOF-34/ctDNA_pypeliner/r_scripts/'